[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "numintegrate"
version = "0.1.0"
authors = [
  { name="Sılanur Çayır", email="silanurcayir@gmail.com" },
]
description = "A Python library for numerical integration methods."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "numpy>=1.20",
]

[project.urls]
"Homepage" = "https://github.com/silanurcayir/numintegrate"
"Bug Tracker" = "https://github.com/silanurcayir/numintegrate/issues"
